### ISSUE TITLE
Chat, AI API and Embedding not working

### ISSUE THREAD

**Issue by SyntecDTx** [supabase-community/chatgpt-your-files#30]
# Bug report

## Describe the bug

The Amount of ebbendings in the documents_section is never full. It Varies from 4 to 15 rows who have a vector embbeding. Others are NULL. Also the Chat is not working. I can type in the Questions, but only see the dots moving for 1-3 Seconds/ 1/2 animation rotations. 

Moreover, when I use the new "const model = new Supabase.ai.Session('gte-small');" I get 0 vector embeddings. With the old one I atleast got some ...

Would be nice if you can help me out. 
 
<img width="1507" alt="Bildschirm­foto 2024-05-18 um 19 01 00" src="https://github.com/supabase-community/chatgpt-your-files/assets/159577716/040923a7-5009-4a63-b96e-efb96a833c32">

<img width="1219" alt="Bildschirm­foto 2024-05-18 um 19 01 19" src="https://github.com/supabase-community/chatgpt-your-files/assets/159577716/9dd23f83-3e97-4475-9d68-27c021ccf82e">

**Comment by gregnr** [comment]
Hey @SyntecDTx,

- The partial `NULL` embeddings is most likely caused by this previous [CPU limit issue](https://github.com/supabase-community/chatgpt-your-files/issues/2). This issue was solved using the new `Supabase.ai.Session()` API.
- If `Supabase.ai.Session()` doesn't work, try checking which version of the edge runtime you are running:
  ```shell
  npx supabase services
   ```

  You will need to be on at least version [v1.40.4](https://github.com/supabase/edge-runtime/releases/tag/v1.40.4), but the latest version is recommended.

  If you're below that version, upgrade your `supabase` CLI:
  ```shell
  npm i -D supabase
  ```

  You can read more info [here](https://github.com/supabase-community/chatgpt-your-files/issues/2#issuecomment-2071068094).

Let me know if this helps!

**Comment by SyntecDTx** [comment]
Thank you for your Answere. I checked the version. I am currently on v1.49 so this should be fine. In the attached Image you can see the Terminal Problem. Also it is ounderlined in curly red :(

<img width="687" alt="Bildschirm­foto 2024-05-19 um 01 16 30" src="https://github.com/supabase-community/chatgpt-your-files/assets/159577716/90c94f93-7f7a-4dc4-9b35-863fcbec3df5">

**Comment by SyntecDTx** [comment]
Hi, i just followed your steps of the linked ressource. Thank you very much. stopping superbase seems to be working! Thank you :)
